name: Third

on:
  workflow_run:
    workflows: ["second"]
    types:
      - completed

jobs:
  test:
    if: ${{github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running after the second workflow!"
